name: lofi
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.17
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.6
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.11.1
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blas=2.122
  - blas-devel=3.9.0
  - blosc=1.21.5
  - branca=0.7.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cuda-cccl=12.4.127
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.4.127
  - cuda-runtime=11.8.0
  - cycler=0.12.1
  - datasets=2.18.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - filelock=3.13.4
  - fiona=1.9.6
  - fmt=10.2.1
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.1
  - fsspec=2024.2.0
  - gdal=3.8.4
  - geopandas=0.14.3
  - geopandas-base=0.14.3
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.0
  - glib-tools=2.80.0
  - gst-plugins-base=1.24.1
  - gstreamer=1.24.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - huggingface_hub=0.22.2
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2024.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.10
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libarchive=3.7.2
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=18.1.3
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.20
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.8.4
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.9.2
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libparquet=15.0.2
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - lightning=2.2.2
  - lightning-utilities=0.11.2
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - minizip=4.0.5
  - mkl=2024.1.0
  - mkl-devel=2024.1.0
  - mkl-include=2024.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - orc=2.0.0
  - packaging=24.0
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.0
  - ply=3.11
  - poppler=24.03.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - proj=9.3.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=15.0.2
  - pyarrow-hotfix=0.6
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - pytorch-lightning=2.2.2
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=26.0.0
  - qt-main=5.15.8
  - re2=2023.09.01
  - regex=2023.12.25
  - requests=2.31.0
  - rtree=1.2.0
  - safetensors=0.4.2
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - setuptools=69.5.1
  - shapely=2.0.3
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.0
  - spdlog=1.12.0
  - sqlite=3.45.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.12.0
  - threadpoolctl=3.4.0
  - tiledb=2.21.2
  - tk=8.6.13
  - tokenizers=0.15.2
  - toml=0.10.2
  - tomli=2.0.1
  - torchmetrics=1.3.2
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - transformers=4.39.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - affine==2.4.0
      - rasterio==1.3.10
      - snuggs==1.4.7
      - torchaudio==2.2.2
      - torchvision==0.17.2
