from yacs.config import CfgNode as CN

_C = CN()

# Data Sequence
_C.DATA = CN()
_C.DATA.GPS_GALLERY = "/data/hkerner/NASA-MLCommons/lofi/dataset/coordinates_100K.csv"
_C.DATA.TRAIN_PATH = "/data/hkerner/NASA-MLCommons/lofi_dataset/train.csv"
_C.DATA.VALIDATION_PATH = "/data/hkerner/NASA-MLCommons/lofi_dataset/validation.csv"
_C.DATA.TEST_PATH = "/data/hkerner/NASA-MLCommons/lofi_dataset/test.csv"

_C.DATA.IMAGE = CN()
_C.DATA.IMAGE.SIZE = 512
_C.DATA.IMAGE.CHANNELS = 6


# Model
_C.MODEL = CN()
_C.MODEL.SEED_VALUE = 43

# Pretraining Image Encoder
_C.MODEL.SSL = CN()
_C.MODEL.SSL.CHECKPOINT_PATH = "/data/hkerner/NASA-MLCommons/lofi/logs/ssl/lightning_logs/version_15143060/checkpoints/epoch=41-step=56826.ckpt"
_C.MODEL.SSL.TRAINING = CN()
_C.MODEL.SSL.TRAINING.LEARNING_RATE = 3e-5
_C.MODEL.SSL.TRAINING.WEIGHT_DECAY = 1e-6
_C.MODEL.SSL.TRAINING.BATCH_SIZE = 64
_C.MODEL.SSL.TRAINING.MAX_EPOCHS = 60
_C.MODEL.SSL.TRAINING.NUM_WORKERS = 8
_C.MODEL.SSL.TRAINING.SWA_LRS = 1e-3

_C.MODEL.SSL.VALIDATION = CN()
_C.MODEL.SSL.VALIDATION.BATCH_SIZE = 32
_C.MODEL.SSL.VALIDATION.NUM_WORKERS = 4


# Pretraining Image and Location Encoder
_C.MODEL.PIL = CN()
_C.MODEL.PIL.CHECKPOINT_PATH = "/data/hkerner/NASA-MLCommons/lofi/logs/pretrain_image_location/lightning_logs/version_15268794/checkpoints/epoch=40-step=49323.ckpt"
_C.MODEL.PIL.TRAINING = CN()
_C.MODEL.PIL.TRAINING.LEARNING_RATE = 3e-6
_C.MODEL.PIL.TRAINING.WEIGHT_DECAY = 1e-7
_C.MODEL.PIL.TRAINING.BATCH_SIZE = 72
_C.MODEL.PIL.TRAINING.MAX_EPOCHS = 60
_C.MODEL.PIL.TRAINING.NUM_WORKERS = 8
_C.MODEL.PIL.TRAINING.SWA_LRS = 1e-4

_C.MODEL.PIL.VALIDATION = CN()
_C.MODEL.PIL.VALIDATION.BATCH_SIZE = 32
_C.MODEL.PIL.VALIDATION.NUM_WORKERS = 4


# Instance Segmentation Training
_C.MODEL.IS = CN()
_C.MODEL.IS.CHECKPOINT_PATH = None
_C.MODEL.IS.TRAINING = CN()
_C.MODEL.IS.TRAINING.LEARNING_RATE = 1e-4
_C.MODEL.IS.TRAINING.WEIGHT_DECAY = 1e-6
_C.MODEL.IS.TRAINING.BATCH_SIZE = 1
_C.MODEL.IS.TRAINING.MAX_EPOCHS = 20
_C.MODEL.IS.TRAINING.NUM_WORKERS = 4
_C.MODEL.IS.TRAINING.SWA_LRS = 1e-3

# Supervised Learning Validation
_C.MODEL.IS.VALIDATION = CN()
_C.MODEL.IS.VALIDATION.BATCH_SIZE = 1  
_C.MODEL.IS.VALIDATION.NUM_WORKERS = 4

# Semantic Segmentation Training
_C.MODEL.SS = CN()
_C.MODEL.SS.CHECKPOINT_PATH = "/data/hkerner/NASA-MLCommons/lofi/logs/semantic_segmentation/lightning_logs/version_15364110/checkpoints/epoch=21-step=59532.ckpt"
_C.MODEL.SS.TRAINING = CN()
_C.MODEL.SS.TRAINING.LEARNING_RATE = 1e-4
_C.MODEL.SS.TRAINING.WEIGHT_DECAY = 1e-6
_C.MODEL.SS.TRAINING.BATCH_SIZE = 32
_C.MODEL.SS.TRAINING.MAX_EPOCHS = 30
_C.MODEL.SS.TRAINING.NUM_WORKERS = 8
_C.MODEL.SS.TRAINING.SWA_LRS = 1e-3

# Supervised Learning Validation
_C.MODEL.SS.VALIDATION = CN()
_C.MODEL.SS.VALIDATION.BATCH_SIZE = 32  
_C.MODEL.SS.VALIDATION.NUM_WORKERS = 4

# Semantic Segmentation UNET Training
_C.MODEL.SSU = CN()
_C.MODEL.SSU.CHECKPOINT_PATH = "/data/hkerner/NASA-MLCommons/lofi/logs/semantic_segmentation_unet/lightning_logs/version_15389555/checkpoints/epoch=15-step=27712.ckpt"
_C.MODEL.SSU.TRAINING = CN()
_C.MODEL.SSU.TRAINING.LEARNING_RATE = 1e-4
_C.MODEL.SSU.TRAINING.WEIGHT_DECAY = 1e-6
_C.MODEL.SSU.TRAINING.BATCH_SIZE = 50
_C.MODEL.SSU.TRAINING.MAX_EPOCHS = 15
_C.MODEL.SSU.TRAINING.NUM_WORKERS = 8
_C.MODEL.SSU.TRAINING.SWA_LRS = 1e-3

# Supervised Learning Validation
_C.MODEL.SSU.VALIDATION = CN()
_C.MODEL.SSU.VALIDATION.BATCH_SIZE = 24  
_C.MODEL.SSU.VALIDATION.NUM_WORKERS = 4


# Semantic Segmentation UNET Training with Location
_C.MODEL.SSUL = CN()
_C.MODEL.SSUL.CHECKPOINT_PATH = "/data/hkerner/NASA-MLCommons/lofi/logs/semantic_segmentation_unet_withlocation/lightning_logs/version_15389555/checkpoints/epoch=15-step=25981.ckpt"
_C.MODEL.SSUL.TRAINING = CN()
_C.MODEL.SSUL.TRAINING.LEARNING_RATE = 1e-4
_C.MODEL.SSUL.TRAINING.WEIGHT_DECAY = 1e-6
_C.MODEL.SSUL.TRAINING.BATCH_SIZE = 50
_C.MODEL.SSUL.TRAINING.MAX_EPOCHS = 15
_C.MODEL.SSUL.TRAINING.NUM_WORKERS = 8
_C.MODEL.SSUL.TRAINING.SWA_LRS = 1e-3

# Supervised Learning Validation
_C.MODEL.SSUL.VALIDATION = CN()
_C.MODEL.SSUL.VALIDATION.BATCH_SIZE = 24  
_C.MODEL.SSUL.VALIDATION.NUM_WORKERS = 4
